#
#
# GommeSagt's configuration file 
# 
# About editing this file: 
# - DO NOT USE TABS. You MUST use spaces or Bukkit will complain. If 
#   you use an editor like Notepad++ (recommended for Windows users), you 
#   must configure it to "replace tabs with spaces." In Notepad++, this can 
#   be changed in Settings > Preferences > Language Menu. 
# - Don't get rid of the indents. They are indented so some entries are 
#   in categories (like "max-blocks-changed" is in the "limits" 
#   category. 
# - If you want to check the format of this file before putting it 
#   into WorldEdit, paste it into http://yaml-online-parser.appspot.com/ 
#   and see if it gives "ERROR:". 
# - Lines starting with # are commentsand so they are ignored. 
#
#

position:
  1:
    x: 0.0
    y: 0.0
    z: 0.0