name: GommeSagt
version: 0.3-ALPHA
authors: [Crystal, Manuey, SimonSky]
website: http://pixelcrew.org

main: org.pixelcrew.gs.Main

commands:
  gspos:
    description: GommeSagt Position
    usage: /gspos [META]
    permission: gommesagt.pos
  gss:
    description: Straf Item
    usage: /gsgive
  gommesagtstrafen:
    description: Strafauswahl
    usage: /<command>
  gommegive:
    description: GommeSagt Item
    
permissions:
  gommesagt.pos:
    default: op
  gommesagt.item:
    default: op