name: GommeSagt
version: 0.2-ALPHA
authors: [Crystal, Manuey, SimonSky]
website: http://pixelcrew.org

main: org.pixelcrew.gs.Main

commands:
  gspos:
    description: GommeSagt Position
    usage: /gspos [META]
    permission: gommesagt.pos

  gommesagt:
    description: GommeSagt Items
    permission: gommesagt.gommesagt
    
permissions:
  gommesagt.pos:
    default: op