name: GommeSagt
version: 0.4-ALPHA
authors: [Crystal, Manuey, SimonSky]
website: http://pixelcrew.org

main: org.pixelcrew.gs.Main

commands:
  gspos:
    description: GommeSagt Position
    usage: /gspos [META]
    permission: gommesagt.pos
  gsitem:
    description: GommeSagt Item
    usage: /gsitem
    permission: gommesagt.item
    
permissions:
  gommesagt.pos:
    default: op
  gommesagt.item:
    default: op