name: GommeSagt
version: 0.3-ALPHA
authors: [Crystal, Manuey, SimonSky]
website: http://pixelcrew.org

main: org.pixelcrew.gs.Main

commands:
  gspos:
    description: GommeSagt Position
    usage: /gspos [META]
    permission: gommesagt.pos
  gommesagt:
    description: GommeSagt Position
    permission: gommesagt.pos
  gommegive:
    description: GommeSagt Items
    
permissions:
  gommesagt.pos:
    default: op