name: GommeSagt
version: 0.3-ALPHA
authors: [Crystal, Manuey, SimonSky]
website: http://pixelcrew.org

main: org.pixelcrew.gs.Main

commands:
  gspos:
    description: GommeSagt Position
    usage: /gspos [META]
    permission: gommesagt.pos
  gsgive:
    description: GommeSagt Item
    usage: /gsgive
    permission: gommesagt.item
    
permissions:
  gommesagt.pos:
    default: op
  gommesagt.item:
    default: op